FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ["src/Fitzo.API/Fitzo.API.csproj", "src/Fitzo.API/"]
COPY ["src/Fitzo.Shared/Fitzo.Shared.csproj", "src/Fitzo.Shared/"]

RUN dotnet restore "src/Fitzo.API/Fitzo.API.csproj"
COPY . .

FROM build AS publish
RUN dotnet publish "Fitzo.API.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app

COPY --from=publish /app/publish .

EXPOSE 8080
ENV ASPNETCORE_HTTP_PORTS=8080

ENTRYPOINT ["dotnet", "Fitzo.API.dll"]