@Fitzo_API_HostAddress = http://localhost:5123
GET {{Fitzo_API_HostAddress}}/api/product/apple
Accept: application/json

GET {{Fitzo_API_HostAddress}}/api/product/apple
Accept: application/json


GET {{Fitzo_API_HostAddress}}/api/product/search/3103220048658
Accept: application/json

GET {{Fitzo_API_HostAddress}}/api/product/search/apple
Accept: application/json




GET {{Fitzo_API_HostAddress}}/api/product/cabbage
Accept: application/json


GET {{Fitzo_API_HostAddress}}/api/product/5900020001882
Accept: application/json

GET {{Fitzo_API_HostAddress}}/api/product/search/0000000000
Accept: application/json