CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260122152959_ChangingAvatarUrl') THEN
    CREATE TABLE "AspNetRoles" (
        "Id" uuid NOT NULL,
        "Name" character varying(256),
        "NormalizedName" character varying(256),
        "ConcurrencyStamp" text,
        CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260122152959_ChangingAvatarUrl') THEN
    CREATE TABLE "AspNetUsers" (
        "Id" uuid NOT NULL,
        "Role" integer NOT NULL,
        "UserName" character varying(256),
        "NormalizedUserName" character varying(256),
        "Email" character varying(256),
        "NormalizedEmail" character varying(256),
        "EmailConfirmed" boolean NOT NULL,
        "PasswordHash" text,
        "SecurityStamp" text,
        "ConcurrencyStamp" text,
        "PhoneNumber" text,
        "PhoneNumberConfirmed" boolean NOT NULL,
        "TwoFactorEnabled" boolean NOT NULL,
        "LockoutEnd" timestamp with time zone,
        "LockoutEnabled" boolean NOT NULL,
        "AccessFailedCount" integer NOT NULL,
        CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260122152959_ChangingAvatarUrl') THEN
    CREATE TABLE "FoodEntries" (
        "Id" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "Date" timestamp without time zone NOT NULL,
        "MealType" integer NOT NULL,
        "ProductEntry_ExternalId" text NOT NULL,
        "ProductEntry_Name" text NOT NULL,
        "ProductEntry_brand" text,
        "ProductEntry_ImageUrl" text,
        "ProductEntry_Calories" double precision NOT NULL,
        "ProductEntry_Protein" double precision NOT NULL,
        "ProductEntry_Fat" double precision NOT NULL,
        "ProductEntry_Carbs" double precision NOT NULL,
        "ProductEntry_Category" integer NOT NULL,
        "ProductEntry_ServingSize" double precision,
        "ProductEntry_ServingUnit" text NOT NULL,
        "ProductEntry_NutriScore" text,
        "ProductEntry_EcoScore" text,
        "ProductEntry_HasPalmOil" boolean,
        "ProductEntry_labels" text[] NOT NULL,
        "ProductEntry_Allergens" text[] NOT NULL,
        "ProductEntry_DataQualityMessages" text[] NOT NULL,
        "ProductEntry_IsDataComplete" boolean NOT NULL,
        "Amount" double precision NOT NULL,
        "OriginalRecipeId" uuid,
        "OriginRecipeName" text,
        CONSTRAINT "PK_FoodEntries" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260122152959_ChangingAvatarUrl') THEN
    CREATE TABLE "RecipeComponents" (
        "Id" uuid NOT NULL,
        "Name" text NOT NULL,
        "Discriminator" character varying(21) NOT NULL,
        "RecipeId" uuid,
        "Product_ExternalId" text,
        "Product_Name" text,
        "Product_brand" text,
        "Product_ImageUrl" text,
        "Product_Calories" double precision,
        "Product_Protein" double precision,
        "Product_Fat" double precision,
        "Product_Carbs" double precision,
        "Product_Category" integer,
        "Product_ServingSize" double precision,
        "Product_ServingUnit" text,
        "Product_NutriScore" text,
        "Product_EcoScore" text,
        "Product_HasPalmOil" boolean,
        "Product_labels" text[],
        "Product_Allergens" text[],
        "Product_DataQualityMessages" text[],
        "Product_IsDataComplete" boolean,
        "Amount" double precision,
        "OwnerId" uuid,
        "ImageUrl" text,
        "Tags" integer[],
        "Description" text,
        CONSTRAINT "PK_RecipeComponents" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_RecipeComponents_RecipeComponents_RecipeId" FOREIGN KEY ("RecipeId") REFERENCES "RecipeComponents" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260122152959_ChangingAvatarUrl') THEN
    CREATE TABLE "UserProfiles" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" uuid NOT NULL,
        "Createdate" timestamp without time zone NOT NULL,
        "Weight" double precision NOT NULL,
        "Height" double precision NOT NULL,
        "Age" integer NOT NULL,
        "AvatarUrl" text,
        "Gender" integer NOT NULL,
        CONSTRAINT "PK_UserProfiles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260122152959_ChangingAvatarUrl') THEN
    CREATE TABLE "WeightEntries" (
        "Id" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "Date" timestamp without time zone NOT NULL,
        "Value" double precision NOT NULL,
        CONSTRAINT "PK_WeightEntries" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260122152959_ChangingAvatarUrl') THEN
    CREATE TABLE "AspNetRoleClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoleId" uuid NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260122152959_ChangingAvatarUrl') THEN
    CREATE TABLE "AspNetUserClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" uuid NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260122152959_ChangingAvatarUrl') THEN
    CREATE TABLE "AspNetUserLogins" (
        "LoginProvider" text NOT NULL,
        "ProviderKey" text NOT NULL,
        "ProviderDisplayName" text,
        "UserId" uuid NOT NULL,
        CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
        CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260122152959_ChangingAvatarUrl') THEN
    CREATE TABLE "AspNetUserRoles" (
        "UserId" uuid NOT NULL,
        "RoleId" uuid NOT NULL,
        CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
        CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260122152959_ChangingAvatarUrl') THEN
    CREATE TABLE "AspNetUserTokens" (
        "UserId" uuid NOT NULL,
        "LoginProvider" text NOT NULL,
        "Name" text NOT NULL,
        "Value" text,
        CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
        CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260122152959_ChangingAvatarUrl') THEN
    CREATE TABLE "MealPlans" (
        "Id" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "RecipeId" uuid NOT NULL,
        "Date" timestamp without time zone NOT NULL,
        "StartTime" interval NOT NULL,
        "EndTime" interval NOT NULL,
        "Type" integer NOT NULL,
        CONSTRAINT "PK_MealPlans" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_MealPlans_RecipeComponents_RecipeId" FOREIGN KEY ("RecipeId") REFERENCES "RecipeComponents" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260122152959_ChangingAvatarUrl') THEN
    CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260122152959_ChangingAvatarUrl') THEN
    CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260122152959_ChangingAvatarUrl') THEN
    CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260122152959_ChangingAvatarUrl') THEN
    CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260122152959_ChangingAvatarUrl') THEN
    CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260122152959_ChangingAvatarUrl') THEN
    CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260122152959_ChangingAvatarUrl') THEN
    CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260122152959_ChangingAvatarUrl') THEN
    CREATE INDEX "IX_MealPlans_RecipeId" ON "MealPlans" ("RecipeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260122152959_ChangingAvatarUrl') THEN
    CREATE INDEX "IX_RecipeComponents_RecipeId" ON "RecipeComponents" ("RecipeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260122152959_ChangingAvatarUrl') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260122152959_ChangingAvatarUrl', '8.0.10');
    END IF;
END $EF$;
COMMIT;

