@startuml Fitzo
!include .\\src\Fitzo.API\Program.puml
!include .\\src\Fitzo.Functions\Program.puml
!include .\\src\Fitzo.API\Controllers\AuthController.puml
!include .\\src\Fitzo.API\Controllers\AvatarController.puml
!include .\\src\Fitzo.API\Controllers\DiaryController.puml
!include .\\src\Fitzo.API\Controllers\ExportController.puml
!include .\\src\Fitzo.API\Controllers\PlanningController.puml
!include .\\src\Fitzo.API\Controllers\ProductController.puml
!include .\\src\Fitzo.API\Controllers\RecipesController.puml
!include .\\src\Fitzo.API\Controllers\StatsController.puml
!include .\\src\Fitzo.API\Controllers\UserController.puml
!include .\\src\Fitzo.API\Controllers\WeightController.puml
!include .\\src\Fitzo.API\Data\DBContext.puml
!include .\\src\Fitzo.API\Entities\FoodEntry.puml
!include .\\src\Fitzo.API\Entities\Ingredient.puml
!include .\\src\Fitzo.API\Entities\MealPlanEntry.puml
!include .\\src\Fitzo.API\Entities\Recipe.puml
!include .\\src\Fitzo.API\Entities\RecipeComponent.puml
!include .\\src\Fitzo.API\Entities\UserIdentity.puml
!include .\\src\Fitzo.API\Entities\UserProfile.puml
!include .\\src\Fitzo.API\Entities\WeightEntry.puml
!include .\\src\Fitzo.API\Interfaces\IBmrStrategy.puml
!include .\\src\Fitzo.API\Interfaces\INutritionProvider.puml
!include .\\src\Fitzo.API\Interfaces\IRecipeBuilder.puml
!include .\\src\Fitzo.API\Interfaces\IRecipeManager.puml
!include .\\src\Fitzo.API\Interfaces\IShoppingListGenerator.puml
!include .\\src\Fitzo.API\Interfaces\IStaticticservice.puml
!include .\\src\Fitzo.API\Interfaces\IUserContextService.puml
!include .\\src\Fitzo.API\Mappings\ProfileMapping.puml
!include .\\src\Fitzo.API\Patterns\RecipeDirector.puml
!include .\\src\Fitzo.API\Patterns\StandardRecipeBuilder.puml
!include .\\src\Fitzo.API\Services\AuthService.puml
!include .\\src\Fitzo.API\Services\BlobStorageService.puml
!include .\\src\Fitzo.API\Services\BmrService.puml
!include .\\src\Fitzo.API\Services\CachingNuritionProxy.puml
!include .\\src\Fitzo.API\Services\CalendarService.puml
!include .\\src\Fitzo.API\Services\CategoryMapper.puml
!include .\\src\Fitzo.API\Services\ExportImportService.puml
!include .\\src\Fitzo.API\Services\HybridNutritionProvider.puml
!include .\\src\Fitzo.API\Services\ImageAvatarService.puml
!include .\\src\Fitzo.API\Services\OffAdapter.puml
!include .\\src\Fitzo.API\Services\OffJsonModel.puml
!include .\\src\Fitzo.API\Services\ProfileImageService.puml
!include .\\src\Fitzo.API\Services\RecipeImageService.puml
!include .\\src\Fitzo.API\Services\RecipeManager.puml
!include .\\src\Fitzo.API\Services\RecipeProtectionProxy.puml
!include .\\src\Fitzo.API\Services\RecipeService.puml
!include .\\src\Fitzo.API\Services\ShoppingListGenerator.puml
!include .\\src\Fitzo.API\Services\UsdaAdapter.puml
!include .\\src\Fitzo.API\Services\UsdaModels.puml
!include .\\src\Fitzo.API\Services\UserContextService.puml
!include .\\src\Fitzo.Functions\Functions\ImageFormat.puml
!include .\\src\Fitzo.Shared\Dtos\AddMealDto.puml
!include .\\src\Fitzo.Shared\Dtos\AddWeightDto.puml
!include .\\src\Fitzo.Shared\Dtos\CreateRecipeDto.puml
!include .\\src\Fitzo.Shared\Dtos\FoodEntryDto.puml
!include .\\src\Fitzo.Shared\Dtos\IngredientDto.puml
!include .\\src\Fitzo.Shared\Dtos\LoginDto.puml
!include .\\src\Fitzo.Shared\Dtos\ProductDto.puml
!include .\\src\Fitzo.Shared\Dtos\ProductSearchFilterDto.puml
!include .\\src\Fitzo.Shared\Dtos\RegisterDto.puml
!include .\\src\Fitzo.Shared\Dtos\ShopingListItemDto.puml
!include .\\src\Fitzo.Shared\Dtos\StatisticsDto.puml
!include .\\src\Fitzo.Shared\Dtos\StatsDto.puml
!include .\\src\Fitzo.Shared\Dtos\UserDto.puml
!include .\\src\Fitzo.Shared\Dtos\UserProfileDto.puml
!include .\\src\Fitzo.Shared\Enums\BmrFormula.puml
!include .\\src\Fitzo.Shared\Enums\DietTag.puml
!include .\\src\Fitzo.Shared\Enums\FoodCategories.puml
!include .\\src\Fitzo.Shared\Enums\Gender.puml
!include .\\src\Fitzo.Shared\Enums\MealType.puml
!include .\\src\Fitzo.Shared\Enums\UserRole.puml
!include .\\src\Fitzo.API\Patterns\Validation\DataIntegrityValidator.puml
!include .\\src\Fitzo.API\Patterns\Validation\ImageValidator.puml
!include .\\src\Fitzo.API\Patterns\Validation\IngredientsCountValidator.puml
!include .\\src\Fitzo.API\Patterns\Validation\RecipeValidationHandler.puml
!include .\\src\Fitzo.API\Services\BMR\Harris-Benedict.puml
!include .\\src\Fitzo.API\Services\BMR\MifflinStJeorStrategy.puml
@enduml
