@startuml
class OffAdapter {
    + OffAdapter(_httpClient:HttpClient)
    + <<virtual>> <<async>> GetProductAsync(id:string) : Task<ProductDto>
    + <<virtual>> <<async>> SearchProductsAsync(filter:ProductSearchFilterDto) : Task<IEnumerable<ProductDto>>
}
INutritionProvider <|-- OffAdapter
@enduml
