@startuml
class RecipeImageService {
    + RecipeImageService(blobServiceClient:BlobServiceClient)
    + <<async>> EnsureContainersExistAsync() : Task
}
BlobStorageService <|-- RecipeImageService
@enduml
